### ISSUE TITLE
error while deleting points after resume measure

### ISSUE THREAD

**Issue by EyalYahav** [ppete2/Leaflet.PolylineMeasure#100]
hello, I've noticed an error while resuming the measure and try to delete a point. The error is: 
**Uncaught TypeError: Cannot read properties of undefined (reading 'lat')
    at Object.distance (CRS.Earth.js:26:22)
    at v.distanceTo (LatLng.js:76:16)
    at e.<anonymous> (Leaflet.PolylineMeasure.js:1355:93)
    at Array.map (<anonymous>)
    at e._dragCircle (Leaflet.PolylineMeasure.js:1353:57)
    at e.fire (Events.js:195:9)
    at e._fireDOMEvent (Map.js:1452:15)
    at e._handleDOMEvent (Map.js:1401:8)
    at HTMLDivElement.o (DomEvent.js:108:13)**

it occurs also on the demo site https://ppete2.github.io/Leaflet.PolylineMeasure/demo1.html
Is there any way to overcome this error?

thanks :)

**Comment by ppete2** [comment]
You're right, I'll try to figure out the problem

**Comment by Grawl** [comment]
Can confirm that issue

**Comment by EyalYahav** [comment]
> 

What do you mean?

**Comment by cbVirginia** [comment]
I have a solution for when points are deleted.  The _arrPolylines array needs to be re-indexed after a line segment is removed.  Like this:
![image](https://user-images.githubusercontent.com/124825561/217640732-6b3e5f88-3056-41a3-8936-dc0d256b257a.png)
Addition is in green.

**Comment by ppete2** [comment]
@cbVirginia Thanks, but I'm afraid your solution isn't working, at least not in all cases. For example:
Draw a line with 3 points. Then resume this line and delete the 2nd point of the line => error messege in console appears
Any idea?
