### ISSUE TITLE
[Suggestion] Have the option to make the plugin on by deafult instead of off.

### ISSUE THREAD

**Issue by ElSabio97** [ppete2/Leaflet.PolylineMeasure#102]
It would be useful to have the plugin already on when the map first loads.

**Comment by ppete2** [comment]
Sorry, this is not a good idea. The plugin (and its reaction to mouseclicks etc.) should just be turned on by the user's request by turning on the measure-switch.

**Comment by ElSabio97** [comment]
I understand. The suggestion was oriented to have _just the option_.

I totally agree with you, the default option should be `off` but for some applications it may be interesting to have it `on` by default.

**Comment by jayli3n** [comment]
Just turn is on via code `polylineMeasure.toggleMeasure()`
