### ISSUE TITLE
TypeError: L.control.polylineMeasure is not a function (installed using npm)

### ISSUE THREAD

**Issue by Sadi-1992** [ppete2/Leaflet.PolylineMeasure#11]
I've tried to use this in AngularJs. 

I've added 
```
"dependencies": {
    "leaflet.polylinemeasure": "^1.0.0"
 }
```
to the package,json and installed it using npm install.

But if i want to use it it returns an TypeError. `L.control.polylineMeasure is not a function`

**Comment by ppete2** [comment]
Sorry, i'm no expert in Packages, npm and so on. You'll have to wait until an expert could help you with the problem.

**Comment by ppete2** [comment]
closed due to lack of feedback.
