### ISSUE TITLE
Syntax error in Internet Explorer

### ISSUE THREAD

**Issue by TomasSkoie** [ppete2/Leaflet.PolylineMeasure#12]
Hi!

There is a syntax error on line 770 when testing in Internet Explorer:

lineCoords.splice ((circleNr-1)*(arcpoints-1), arcpoints, ...newLineSegment1);

I don't think the spread operator (...) is widely supported.

**Comment by ppete2** [comment]
Thanks, rewrote some lines to make plugin runnin with granddad Internet Explorer too.
