### ISSUE TITLE
Use on mobile devices

### ISSUE THREAD

**Issue by Poldy1705** [ppete2/Leaflet.PolylineMeasure#13]
I tried it on mobile devices. You cannot reach the icon to stop the function.

**Comment by ppete2** [comment]
I tried it, and it's working on touch screens too. The control buttons on the left side are no problem at all (you can click on the measurement button to finsh drawing a line). But It was indeed hard during drawing to hit the actual circle to finish the line. So I increased the radius of the actual circle.

What is not working on touch devices yet is to move the points and correct their position on the map. I'll do some recherches if and how this is possible at all.

**Comment by Poldy1705** [comment]
Thanks a lot!
