### ISSUE TITLE
click on "Clear measurments" button, (without draw anything), throws an exception

### ISSUE THREAD

**Issue by iofirag** [ppete2/Leaflet.PolylineMeasure#16]
click on "Clear measurments" button, (without draw anything), throws an exception.

can see it in the official example page:
https://ppete2.github.io/Leaflet.PolylineMeasure/demo1.html

just click on "Clear measurments" button, (without draw anything)
and you will get the exception in your console:

> Uncaught TypeError: Cannot read property 'finalize' of undefined
>     at e._finishPath (Leaflet.PolylineMeasure.js:760)
>     at e._clearAllMeasurements (Leaflet.PolylineMeasure.js:417)
>     at HTMLAnchorElement.r (DomEvent.js:81)

**Comment by ppete2** [comment]
Hello, thanks, fixed!
