### ISSUE TITLE
Once created, moving a polyline measure breaks mouse move events propagation

### ISSUE THREAD

**Issue by aludin** [ppete2/Leaflet.PolylineMeasure#19]
Hello,
First just wanted to say that your plugin is awesome! It fills all my needs, especially nautical miles measures. 

I am having an issue and at the moment not sure whether its due to an error on my part. Here is how to reproduce it:

1. register a map mouse move listener:

 `map.on('mousemove', function(e){console.log('mouse move: '+e.latlng.lat+' '+e.latlng.lng)});`

This works as expected and the mouse move events are shown in the console.

2. Create a polyline measure. Works awesome.

3. Select the tip of the polyline measure and move it to another location. You will notice that the mouse move events are no longer propagated in the console. 

This is an issue for me because I use those events to display the current pointer lat/lng on the map. 

Any workarounds to this issue would be greeatly  appreciated!  If I could stop the user from actually moving the polyline measure, that would be also fine, as long as I don't lose the mouse move events

*Edit:*
The problem seems to happen at the end of the `_dragCircle` method:

```
self._map.on ('mouseup', function () { 
                    self._resetPathVariables();
                    self._map.off ('mousemove');
                    self._map.dragging.enable();
                    self._map.on ('mousemove', self._mouseMove, self);
                    self._map.off ('mouseup');
                });

```

Thanks!

**Comment by ppete2** [comment]
Thanks, I think I fixed your problem, could you please check it?
