### ISSUE TITLE
Polyline node clicking bug

### ISSUE THREAD

**Issue by erkinsergey** [ppete2/Leaflet.PolylineMeasure#2]
If i click on the some node polyline by drawing, i have exceptions: 
Uncaught TypeError: Cannot read property 'next' of undefined
Uncaught TypeError: Cannot read property 'min' of undefined
Uncaught TypeError: Cannot read property 'lat' of undefined
After that, the work with map goes wrong: [https://ppete2.github.io/Leaflet.PolylineMeasure/demo_metric.html](https://ppete2.github.io/Leaflet.PolylineMeasure/demo_metric.html)

**Comment by ppete2** [comment]
I don't think that this exceptions are caused by the plugin, cause there's not such property "next".

Could you please describe in detail which Website you are using, which browser, which clicks you are doing when using the plugin, where you can see the windows with the execptions you mentioned above.

**Comment by erkinsergey** [comment]
Please click the some small black dot on the polyine In the [demo](https://ppete2.github.io/Leaflet.PolylineMeasure/demo_metric.html) after drawing and see browser debug console.

**Comment by ppete2** [comment]
Hello, I fixed it, meaning no more exceptions in the browser debug console. Could you check it too if it's working now?
Still a tiny optical problem: When hovering the green and black dots the cursor changes into a hand. That's a problem of Leaflet itself cause a former interactive Circle couldn't be switched non-interactive again, I'll drop them an issue note.

**Comment by erkinsergey** [comment]
Thanks, it works! 
Still there is an idea - freely to move points of a polyline and to recalculate distances between them.
Good luck!
