### ISSUE TITLE
Lines are drawn straight, without arc

### ISSUE THREAD

**Issue by mladenp** [ppete2/Leaflet.PolylineMeasure#20]
I implemented this library inside my project but it doesn't draw lines as arcs but as straight lines.
Here is screenshot: https://i.imgur.com/LNrwGqQ.jpg
I am not sure where to start debugging this?

**Comment by ppete2** [comment]
Hello, please provide a Link to your site, that we can see how you added the addon to your site.

**Comment by mladenp** [comment]
I am not able to share that but i added it via npm and added it to map like so:
`L.control.polylineMeasure(measureToolOptions).addTo(this.map);`
@ppete2 can you point me in a direction where should i look to fix this? 
I did not change leaflet map coordinate system, default one is used.

**Comment by ppete2** [comment]
I'm not an npm-Expert so I can't tell you if the adding using npm is maybe the source of your problem.

But you can download the whole ressource of the addon from Github, put it onto your Website, and set the links of your site to load these local files. 

Is it working now?

**Comment by mladenp** [comment]
@ppete2 you are right, npm package is not updated. 
I'll look tomorrow into helping you publish this on npm the correct way, as i need it in package manager.
Thanks

**Comment by mladenp** [comment]
Someone already published this on npm but its not auto publishing latest changes, so i just published one with current changes for myself.
