### ISSUE TITLE
multiple maps on one page

### ISSUE THREAD

**Issue by tstapff** [ppete2/Leaflet.PolylineMeasure#21]
PolylineMeasure doesn't work when it's included on two or more maps on the same HTML page. Example:

http://tile.opengeofiction.net/util/polyline_measure.html

If you click on the measure control in the left map, the right one gets activated. It worked correctly in previous versions, and the current behavior seems to have been introduced in commit 30fa45 (rework state management).

**Comment by ppete2** [comment]
@yrral86 could you please have a look at https://github.com/ppete2/Leaflet.PolylineMeasure/issues/21
I think the issue has something to do with the modifications of this commit, cause before it has been possible to use Polyline.measure at multiple maps on one page, thank you.

**Comment by yrral86** [comment]
@ppete2 @tstapff 
Sorry for the delay.  I missed the notification and happened across this today.

This PR should address the issue: #29

**Comment by ppete2** [comment]
Thanks @yrral86 ! Problem fixed.
