### ISSUE TITLE
Leaflet measure doesn't work on Internet Explorer 11

### ISSUE THREAD

**Issue by mac-call** [ppete2/Leaflet.PolylineMeasure#25]
Leaflet measure doesn't work on Internet Explorer 11
It seems IE doesn't recognize the '=>' js syntax. 

Since it's only used one time in PolylineMeasure, it may be corrected by replacing :
https://github.com/ppete2/Leaflet.PolylineMeasure/blob/12d72303f8b6a1246233c8812501b3fc7a0d85ae/Leaflet.PolylineMeasure.js#L841
with its longer version :  
self._arrArrows[e.target.cntLine].forEach(function(element)  { return self._arrArrowsCurrentline.push(element); });

**Comment by ppete2** [comment]
fixed, thank you for the correction line.
