### ISSUE TITLE
IE includes

### ISSUE THREAD

**Issue by rendrom** [ppete2/Leaflet.PolylineMeasure#3]
https://github.com/ppete2/Leaflet.PolylineMeasure/blob/master/Leaflet.PolylineMeasure.js#L274
https://github.com/ppete2/Leaflet.PolylineMeasure/blob/master/Leaflet.PolylineMeasure.js#L292

Because of this, it is impossible to run in IE (11 in my case) without the polyfill

**Comment by ppete2** [comment]
Thanks, I rewrote the Code, now it is running within Internet Explorer 11 and above too.
