### ISSUE TITLE
Double click cannot stop drawing

### ISSUE THREAD

**Issue by janessssss** [ppete2/Leaflet.PolylineMeasure#34]
After I loaded the Baidu map with the leaflet, I can't stop using double click..What happened?

This has been resolved is the version of the css.

**Comment by janessssss** [comment]
This has been resolved is the version of the css.
Please ask bearingTextIn is the starting coordinate?

**Comment by ppete2** [comment]
Excuse, I don't unterstand what issue you're trying to explain. Please try it again using some more sentences or an example map where we could see the issue.

**Comment by janessssss** [comment]
The previous ones have been solved. I would like to ask how to get all the point coordinate sets drawn.

**Comment by ppete2** [comment]
sorry, I stilll don't understand what Issue you're talking about. Please try to explain it in detail, using an example for me to reproduce. Maybe also attach a screenshot of the problem.
