### ISSUE TITLE
Error on dragging circle 

### ISSUE THREAD

**Issue by tayagorbunova** [ppete2/Leaflet.PolylineMeasure#35]
Hey! I'm using the plugin with AngluarJS and it's works just fine except this.
After drawing a path, I'm trying to drag one of the end-path circles. Map freezes and i see the following error in the console.
`Uncaught TypeError: self._arrArrows[lineNr][circleNr].removeFrom is not a function`

Any ideas what could be wrong?
 
Thanks in advance.

**Comment by ppete2** [comment]
Hi!
You are using an outdated version. In the latest version this problem is solved, and the self._arrArrows variable has been renamed.

**Comment by tayagorbunova** [comment]
I installed the plugin via npm and my current version is 1.0.0. 
Is it possible to update the plugin on npm (cause it seems to have the deprecated version for now)?

**Comment by ppete2** [comment]
Sorry, I'm not competent on taking care of these installers. Either you could update them yourself or ask the person who introduced this special kind of installer for this add-on.
