### ISSUE TITLE
es6 problem

### ISSUE THREAD

**Issue by iofirag** [ppete2/Leaflet.PolylineMeasure#37]
you left es6 arrow function in your code, that break my build process in my project
in Leaflet.PolylineMeasure.js in line 841

need to change from:
`self._arrArrows[e.target.cntLine].forEach(element => { self._arrArrowsCurrentline.push(element); });`

to:
`self._arrArrows[e.target.cntLine].forEach(function (element) { self._arrArrowsCurrentline.push(element); });`

**Comment by ppete2** [comment]
Hello, you're using an outdated version of the code. I changed this already some months ago.

**Comment by iofirag** [comment]
sorry, thanks for your update.

**Comment by plaxdan** [comment]
@ppete2 any chance you could publish this update to npmjs.com. We're pointing directly at the master branch of your repo for the time being.

```json
"leaflet.polylinemeasure": "github:ppete2/Leaflet.PolylineMeasure",
```

**Comment by ppete2** [comment]
Sorry, I'm not familiar with nor responsible to keep these optional package manager installs up-to-date. If you notice that such installs are outdated, feel free to provide a Pull request or contact one of the persons who once introduced those install variants, thanks.
