### ISSUE TITLE
The measurement mode is not switched off.

### ISSUE THREAD

**Issue by erkinsergey** [ppete2/Leaflet.PolylineMeasure#38]
If you click the measurement button when you select the next reference point when measuring the distance, the button will take the original view, but the measurement mode will not disappear.

Try to start the measurement and make another click on the measurement button for this effect.

**Comment by ppete2** [comment]
Hello, sorry I can not quite follow your description. Could you please describe the issue somehting more in detail and/or use screeenshots to demonstrate the issue.

**Comment by erkinsergey** [comment]
Ok, will try. Sorry for my English... 
![measurement1](https://user-images.githubusercontent.com/27002236/38126904-2c2c11a4-33fc-11e8-8721-1342ee98be22.png)

![measurement2](https://user-images.githubusercontent.com/27002236/38126908-312e851a-33fc-11e8-8267-31a0444c5ebf.png)

**Comment by ppete2** [comment]
Hi, now I understand your problem. This one has been solved already months ago, so you're using an outdated version of the plugin. Please update!

**Comment by erkinsergey** [comment]
Thanks for the answer!
I installed the package by 
`npm install --save leaflet.polylinemeasure`
In the package.json was  "version": "2.0.0".

But in the downloaded archive with github -   "version": "1.0.0". But works correctly.
I do not understand...
