### ISSUE TITLE
Uncaught ReferenceError: tooltipStart is not defined

### ISSUE THREAD

**Issue by iofirag** [ppete2/Leaflet.PolylineMeasure#39]
i'm using stenciljs and add your plugin, but then it gave me an errors when i try to use it.
the errors related to variables that was not defined.

Uncaught ReferenceError: tooltipStart is not defined
Uncaught TypeError: self._currentLine.points.last is not a function

it seems that there are missing `var` before the issued variables that the console tell me about them.

**Comment by ppete2** [comment]
I'm afraid you're using an old version of the plugin, have a look at the top-lines of your "Leaflet.PolylineMeasure.js" file. 
Today I wrote a comment-line into this file, which tells users the version of the plugin they are using

**Comment by iofirag** [comment]
you right. sorry. it's happen because i use your [npm](https://www.npmjs.com/package/leaflet.polylinemeasure) package that in version 2.0.0 few month, and not your this repository (from github)

why are you not update your npm repo to be updated as github repo?

**Comment by ppete2** [comment]
sorry, the whole repo and installer stuff is in responsibility of persons who decided to add my addon to their used installers. I'm just resposible for the addon js-code provided via github. 
If people use the addon by the help of external installers they have to care theirself to keep them up-to-date.

**Comment by iofirag** [comment]
ok, so who responsible for the npm package?
