### ISSUE TITLE
Can`t translate units: km, m, ml

### ISSUE THREAD

**Issue by rshadow** [ppete2/Leaflet.PolylineMeasure#41]
Please move the units of measure (`km`, `m`, `ml`, etc) in the options. Like `bindTooltipText`, `measureControlTitleOn`, etc. I need this for translate plugin to other languages.

**Comment by ppete2** [comment]
Hello, I thought those units (m, km, ft, mi, nm) are international - at least in languages using latin alphabet?
Just for interest: which languages are you thinking about?

**Comment by rshadow** [comment]
Russian language. Its look like: `м` `км` `фт` `ми` `нм`. I understand latin units, but my users confused.

**Comment by ppete2** [comment]
Ok, I introduced 2 objects within the options to get variable naming of units
