### ISSUE TITLE
Cannot turn off in iOS/Safari

### ISSUE THREAD

**Issue by ivagon81** [ppete2/Leaflet.PolylineMeasure#42]
Works great on other platforms, But when using Safari on an iPhone device, it is impossible to turn off the PolylineMeasure tool. Do you have any suggestions?

**Comment by ppete2** [comment]
Sorry, since I do not have iOS, I can not tell you the reason. It's working in every other Browser, even the old Internet Explorer. Is it working with Safari on am Mac Desktop or Notebook?

**Comment by ivagon81** [comment]
Thanks for your reply. Some of my coworkers claim that it works fine on a Mac desktop, but not on iPhone or iPad. The behavior I see on iPhone is that when I tap on the button, rather than turning off the tool, it adds another point to the map right below the button. Works perfectly fine on an Android phone though.

**Comment by ppete2** [comment]
One option: Maybe he's using a map which uses an outdated version of the plugin? Please try the latest Demo-Maps here at github
