### ISSUE TITLE
What about mobile devices?

### ISSUE THREAD

**Issue by VladimirKalachikhin** [ppete2/Leaflet.PolylineMeasure#44]
This good for my [map viewer](https://github.com/VladimirKalachikhin/Galadriel-map), but I need to control without keyboard, from touchscreen only.
Is it possible to add, for example, a double-touch to add/remove point and stop/continue drawing?

**Comment by ppete2** [comment]
Sorry, this extra features won't be available on mobile devices. Just the basic functionality.
