### ISSUE TITLE
L.Mixin.Event deprecation warning

### ISSUE THREAD

**Issue by isopropil** [ppete2/Leaflet.PolylineMeasure#47]
With Leaflet 1.3.4 throws a deprecation warning with L.MixinEvents:

Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead

**Comment by ppete2** [comment]
Hello, I can't see such a warning or another one within the JS-console in Firefox and Chrome. How did you see it?

**Comment by lionsoft** [comment]
Confirm. Leaflet 1.4.0. The warning is raised at the line 22 of `Leaflet.PolylineMeasure.js` 
```
L.Control.PolylineMeasure = L.Control.extend({...});
```
in the `leaflet` code 

```
function checkDeprecatedMixinEvents(includes) {
	if (typeof L === 'undefined' || !L || !L.Mixin) { return; }

	includes = isArray(includes) ? includes : [includes];

	for (var i = 0; i < includes.length; i++) {
		if (includes[i] === L.Mixin.Events) {
			console.warn('Deprecated include of L.Mixin.Events: ' +
				'this property will be removed in future releases, ' +
				'please inherit from L.Evented instead.', new Error().stack);
		}
	}
}
```

**Comment by ppete2** [comment]
I again tested the situation by checking [https://ppete2.github.io/Leaflet.PolylineMeasure/demo1.html](https://ppete2.github.io/Leaflet.PolylineMeasure/demo1.html) with Debugger of Firefox and Chrome. I don't get such wanrning. Also the mentioned line 22 does note contain "L.Control.PolylineMeasure = L.Control.extend({...})". Maybe you are using another Website which uses some old code of this addon?
