### ISSUE TITLE
Hide control

### ISSUE THREAD

**Issue by oarque** [ppete2/Leaflet.PolylineMeasure#48]
Hi,
How to hide the polylineMeasure control?
Thanks

**Comment by ppete2** [comment]
It's possible to clear the measurement lines by using the "clear"-button or the "clearMeasurementsOnStop"-option.

But if you want to know how to dynamically remove the control buttons of the plugin after they have been added to Leaflet, I can't help you. You have to ask that in Leaflet support forums.

**Comment by prasanjitdash** [comment]
I understood that you only want to hide its display, but not totally remove it. You may use CSS setting or remove just the container (I use the second approach):
e.g.,
```
	ctlMeasure = L.control.polylineMeasure({
		position: 'topright',
		unit: 'metres',
		showBearings: false,
		clearMeasurementsOnStop: false,
		showClearControl: true,
		showUnitControl: true
	}).addTo(map);
	ctlMeasure._container.remove();
```
CSS/Jquery approach
$('.FIND_THE_NAME_OF_THE_SELECTOR_USING_CHROME').css("display", "none");
