### ISSUE TITLE
can init some data?

### ISSUE THREAD

**Issue by liuchuancong** [ppete2/Leaflet.PolylineMeasure#49]
hello,I want set some data when opened ?

**Comment by ppete2** [comment]
Sorry, I'm no quite sure waht exactly you mean. But saving and restoring of drawed measurements is not possible.

**Comment by liuchuancong** [comment]
ok，thanks！

**Comment by slutske22** [comment]
I know this is hella old, but in light of [this SO question](https://stackoverflow.com/questions/67078270/coordinates-array-from-polylinemeasure-plugin-react-leaflet), I figured out a simple way to restore polyline measurements, assuming the measurements were store in an array, with each entry being an array of `latlng` objects.

```javascript
const pMeasure = L.control.polylineMeasure();
pMeasure.addTo(map);

// Hijack user actions to manually draw polylines
polylines.forEach((polyline) => {
  // toggle draw state on:
  pMeasure._toggleMeasure();
  // start line with first point of each polyline
  pMeasure._startLine(polyline[0]);
  // add subsequent points:
  polyline.forEach((point, ind) => {
    const latLng = L.latLng(point);
    pMeasure._mouseMove({ latLng });
    pMeasure._currentLine.addPoint(latLng);
    // on last point,
    if (ind === polyline.length - 1) {
      pMeasure._finishPolylinePath();
      pMeasure._toggleMeasure();
    }
  });
});

```

## [Working codesandbox](https://codesandbox.io/s/polylinemeasure-from-points-bi80y)

I'm not sure if you have any interest in canonizing this as part of the plugin, by adding a `.fromCoords` method (or something similarly named), which takes in an array of polylines coords, and automatically draws
