### ISSUE TITLE
clearMeasurementsOnStop ERROR TypeError: Cannot read property 'originalEvent' of undefined

### ISSUE THREAD

**Issue by bodryi** [ppete2/Leaflet.PolylineMeasure#50]
Installed dependencies:
-   leaflet@1.3.1
-   leaflet.polylinemeasure@2.0.0

By default in config option `clearMeasurementsOnStop` is set to `true`. When you're setting one or more point (start drawing) and then you want to toggle the measure control, you'll get the error:

```
ERROR TypeError: Cannot read property 'originalEvent' of undefined
    at NewClass._finishOrRestartPath (Leaflet.PolylineMeasure.js:829)
    at NewClass._clearAllMeasurements (Leaflet.PolylineMeasure.js:428)
    at NewClass._toggleMeasure (Leaflet.PolylineMeasure.js:414)
    at HTMLAnchorElement.handler (leaflet-src.js:2280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:17280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1540)
```

In your demo leaflet.polylinemeasure@1.0.0 is used and if I install it, everything works well. 
In https://github.com/ppete2/Leaflet.PolylineMeasure/issues/38 you told that this error has already been solved, but the latest available version has this bug.

UPD In demo you're using files from repo, it seems to me that they are newer than leaflet.polylinemeasure@2.0.0 and didn't published to npm.

UPD2 
changing in package.json from 
```"leaflet.polylinemeasure": "^2.0.0"```
to
 ```"leaflet.polylinemeasure": "git+https://github.com/ppete2/Leaflet.PolylineMeasure.git#master"```
helped to install *latest unpublished to npm* version of this package.

@ppete2, can you publish this version as `2.1.0` for example to npm?

**Comment by ppete2** [comment]
Hello, I just tried it with [https://ppete2.github.io/Leaflet.PolylineMeasure/demo3.html](url) which uses th option `clearMeasurementsOnStop: true`.
On a local copy of this site, I changed option to `clearMeasurementsOnStop: false`.

Both cases are working without errors. So maybe it's because your site which uses the Measure add-on isn't using the latest version of the script? If you open the file "Leaflet.PolylineMeasure.js" you should read _"Version: 2018-10-22"_ in the first lines.

Maybe it's a problem with npm as you mentioned. Please read what I wrote in chapter "Package manager install" in my add-ons manual.

**Comment by bodryi** [comment]
Definitly yes, the problem exists only in npm package `"leaflet.polylinemeasure": "^2.0.0"`, I wrote about it in UPD2 part of my issue.

If I understood you correctly, you're not going to update your plugin at npm registry? I use npm to manage my dependencies, so it will be mush better to mange all of them in the same style.

**Comment by ppete2** [comment]
I'm not going to update npn files myself, since I'm no packet manager expert, and added the packet manager things just because some users asked me to do. If you want updated npn-files, you either have to update them yourself via a Pull request here. Or ask some of the guys, who initially did provide this files, to help you.

**Comment by bodryi** [comment]
@ppete2 OK, I understood. Here's a guide how to publish your package to npm registry: https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600.

Long story short, you need to fill some fields in package.json (most of them are already filled) and then run `npm publish`.

**Comment by ppete2** [comment]
Hi, I think I therefor have to download extra software (npn?) etc... not just change a few textlines at github.
Sorry, but I won't do this. But if you want fix this on your own using npn software, you're welcome. I also did a search for my plugin here: [https://www.npmjs.com/search?q=polyline%20measure](url) and noticed that 3 different entries are refering to my addon. So you perhaps should think about what of them to update - just 1, or each 3 ?

**Comment by bodryi** [comment]
You're only responsible for your own repo and don't need to update any of them. I found, that someone already published your plugin here: https://www.npmjs.com/package/leaflet.polylinemeasure.latest.

It's strange, that third party people need to publish package instead of maintainer, but it's your solution and I have nothing to do with it.

I think, that we can close issue, because it's clear, how to fix this bug. Thank you for quick replies.

**SOLUTION**: install latest version from repo link or find `leaflet.polylinemeasure` published by someone without this bug.

P.S. npm - node package manage, if you're frontend developer, I guess there's 99% that you already have it installed because it's delivered with node.js.
