### ISSUE TITLE
Error when trying to delete the point of polyline during drawing

### ISSUE THREAD

**Issue by bodryi** [ppete2/Leaflet.PolylineMeasure#52]
You draw the polyline and then hover any point of it not exiting out of drawing mode and you see tooltip with message "Press SHIFT-key and click to delete the point". But if you click it nothing happens and you'll get an error at console:
```
Uncaught TypeError: Cannot read property 'circleCoords' of undefined
    at e._dragCircle (Leaflet.PolylineMeasure.js:1195)
    at e.fire (leaflet.js:5)
    at e._fireDOMEvent (leaflet.js:5)
    at e._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.r (leaflet.js:5)
```
Reproduced at any currently available demos.

**Comment by ppete2** [comment]
Confirmed, but dragging or deleting points during drawing mode was initially not intended. This should just be available if a user finished drawing a line.
