### ISSUE TITLE
Could not add point by ctrl-click

### ISSUE THREAD

**Issue by zejafo** [ppete2/Leaflet.PolylineMeasure#63]
Could not create intermidiate point with ctrl-click.

![image](https://user-images.githubusercontent.com/7479125/65534580-73614e00-df08-11e9-87e9-7994df4b89a7.png)

**Comment by zejafo** [comment]
Update.
It works only after finalize, but not when process. So, it should not show the message _press ctrl-click to add point_ while process (only when done) or fix functionality.

**Comment by ppete2** [comment]
you'r right. I'm thinking if it makes sense to add intermediate points also during drawing or if its better to don't show the message.

**Comment by ppete2** [comment]
This issue got solved by correction the behaviour of the tooltips during drawing a line
