### ISSUE TITLE
Dedicated Events to subscribe to

### ISSUE THREAD

**Issue by elmatou** [ppete2/Leaflet.PolylineMeasure#66]
Hello,

Just starting using your this nice plugin.
 
I would like to use the measurements infos (points position, bearings & distance) for later use.
Is there any events I can subscribe to, or any internal object I can observe to get these infos ?

Thx

**Comment by ppete2** [comment]
All the graphs (lines, points, tooltips) are stored in the variable "this._arrPolylines". There yu could get the coordinates of the points.
The bearings and distance are not stored in seperate variables but just stored as part of the text within the tooltips which you can find within "this._arrPolylines[lineNr].tooltips".

But you have to alalyse the source code yourself how to get those infos exactaly, since the plugin is not designed to export those infos outside the plugin.

**Comment by elmatou** [comment]
Thx for your response, I'm gonna figure it out with it.

As for the event part of my question, would you accept a PR with some events triggering mecanism ?
(onStartMeasurement, onEndMeasurement, onAddPoint, onMovePoint...)

Bye

**Comment by ppete2** [comment]
Yes, would be ok. But please be careful to don't crash some features of the plugin which several former PRs by mistake did. And as for the start/end Measurement I think there's already an event or at least a variable which is set.

**Comment by elmatou** [comment]
Hi,
in second thoughts, and as my problematic is pretty specific, i'm not sure my needs will be universal.
but for the record, and for others in need of events, here is my custom control extended from the plugin by overwriting some of the methods : 

```javascript
L.Control.CustomPolylineMeasure = L.Control.PolylineMeasure.extend({
  _dragCircleMouseup: function (e) {
    L.Control.PolylineMeasure.prototype._dragCircleMouseup.call(this, e);
    this._map.fire('polylinemeasure:move', this._arrPolylines[this._lineNr]);
  },

  _clickedArrow: function (e) {
    L.Control.PolylineMeasure.prototype._clickedArrow.call(this, e);
    if (e.originalEvent.ctrlKey) {
      this._map.fire('polylinemeasure:insert', e);
    }
  },

  _dragCircle: function (e) {
    L.Control.PolylineMeasure.prototype._dragCircle.call(this, e);
    if (e.originalEvent.shiftKey) {
      this._map.fire('polylinemeasure:delete', this._arrPolylines[this._lineNr]);
    }
  },

  _finishPolylinePath: function (e) {
    let current = this._currentLine;
    L.Control.PolylineMeasure.prototype._finishPolylinePath.call(this, e);
    this._map.fire('polylinemeasure:finish', current);
  }
});
```

**Comment by elmatou** [comment]
I made a PR for this #68
