### ISSUE TITLE
Line drawn to former location of point

### ISSUE THREAD

**Issue by ewheeless** [ppete2/Leaflet.PolylineMeasure#67]
Click two points to create a path. Press ESC to complete.
Use SHIFT-click to delete either point leaving a single point remaining with distance = 0.
Drag this point to a new location
Use CTRL-click on point to resume building path.  
Add a new point and press ESC to complete.
Note that there is a line drawn between the two points but also to the original location of the origin point.

![image](https://user-images.githubusercontent.com/19333995/67870264-f0ce3e80-fb04-11e9-8b29-7a2875d1fa18.png)

**Comment by ppete2** [comment]
fixed this case by removing the whole line segment if the penultimate point is being deleted.

there's been also a corresponsing bug if resuming a line in the case after an intermediate point were moved or deleted: the total distance had a wrong value. I fixed this too.

**Comment by ewheeless** [comment]
Thanks!
