### ISSUE TITLE
Add ability to display bearings in gradian

### ISSUE THREAD

**Issue by claudep** [ppete2/Leaflet.PolylineMeasure#69]
I would need the ability to display the bearing values in gradian unit, so would love to see a `bearingUnit` option to `PolylineMeasure` init method.

**Comment by ppete2** [comment]
I will think about it. I've never seen a use case in reality where somebody used gradians. Just for interest: what is your use case?

**Comment by claudep** [comment]
I'm working with a forest team and their compasses use gradian units (I did not see them personally).

**Comment by ppete2** [comment]
Very interesting, never seen such one. Could you ask them which compass modell they use? Which country are they from?

**Comment by claudep** [comment]
Here it is! (Switzerland)

![IMG_2629](https://user-images.githubusercontent.com/143192/74515753-7b4d7900-4f0f-11ea-8a5e-9bbe88c10434.jpg)

**Comment by ppete2** [comment]
Thanks, interesting device. Anyway sorry but since gradians are hardly used in real life I won't implement it into the addon.

**Comment by claudep** [comment]
Just to be sure, would you accept a patch for that functionality? Do you think it would be hard to implement?

**Comment by ppete2** [comment]
Sorry, I want to stay with degrees only. The addon is already over-optionised and I don't want to add features which are hardly in use.

**Comment by claudep** [comment]
That makes sense in a maintainer point of view. I'll see if I can maintain a fork with such a modification.

**Comment by claudep** [comment]
If anyone is interested by this feature, note that I added gradians support in this plugin in the branch https://github.com/claudep/Leaflet.PolylineMeasure/tree/gradians
