### ISSUE TITLE
How to pragmatically turn control off?

### ISSUE THREAD

**Issue by BobbyRuby** [ppete2/Leaflet.PolylineMeasure#72]
I tried triggering a click event but that doesn't do it.

Using your plugin to create custom controls for adding polylines to map.

I'm triggering a click event on the control when the polyline finishes... everything works fantastically but the control stays on and I need it to turn off automatically.

**Comment by ppete2** [comment]
Hi Bobby, I'm not quite sure what you tried to explain. Have you tried the Demos? After you finished drawing a line and you click onto the green "arrow" button on the left, the addon got deactivated. Until you click onto the arrow button again. No need to additionally trigger a click event.

**Comment by BobbyRuby** [comment]
I've got it worked out... thanks!  Actually using your control to make custom controls for a telco mapping application.  Thanks again!
