### ISSUE TITLE
Don’t working events in react component

### ISSUE THREAD

**Issue by SuroHak** [ppete2/Leaflet.PolylineMeasure#73]
Doesn't work any event in react component.

[](https://codesandbox.io/embed/leafletpolylinemeasure-doesnt-work-with-hooks-typescript-forked-gr87g?file=/src/PolylineMeasure.tsx:367-372&codemirror=1)

**Comment by ppete2** [comment]
Sorry, I'm not understanding what you mean. Try to explain in more sentences, using examples and maybe Screenshots to describe your problem, thanks.

**Comment by SuroHak** [comment]
https://codesandbox.io/s/leafletpolylinemeasure-doesnt-work-with-hooks-typescript-forked-gr87g?file=/src/PolylineMeasure.tsx

Please see this example.

**Comment by SuroHak** [comment]
There is have any way to access events in the react component?

**Comment by SuroHak** [comment]
?

**Comment by ppete2** [comment]
Sorry, most of the events-stuff got implemented by other users who need them within their skripts. Most of them in Nov. 2019 by user @elmatou . Please contact him to advise you using events, thanks.

**Comment by SuroHak** [comment]
@elmatou can you help me ?

**Comment by SuroHak** [comment]
@ppete2 can I know polyline active or not from map clicks?

**Comment by elmatou** [comment]
Hi,
Your code seem correct, but you are using npm package wich is not up to date.
you can use github source or ask @ppete2 for an npm update.

**Comment by ppete2** [comment]
Thanks @elmatou for helping with his problem.
Regarding npm update, please read [https://github.com/ppete2/Leaflet.PolylineMeasure#package-manager-install](url)

**Comment by SuroHak** [comment]
@ppete2 can we publish a new version?

**Comment by ppete2** [comment]
Sure, but you have to create the necesssary modifications on your own. Either via a PR or by writing me what exactaly and in what file I should modify, since I'm not responsible for npm updates as written I the link above.

**Comment by SuroHak** [comment]
@elmatou can you help with this?

**Comment by elmatou** [comment]
If we can't update the npm repos, just install it from github.
https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

**Comment by SuroHak** [comment]
ok thanks @elmatou )

**Comment by DVGY** [comment]
> If we can't update the npm repos, just install it from github.
> https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

This worked for me!!!!!! Thanks
