### ISSUE TITLE
Use smaller Units for small Maps - centimeters or inches

### ISSUE THREAD

**Issue by Mudo121Bbc** [ppete2/Leaflet.PolylineMeasure#77]
Is it possible the show and measure in smaller Units, e.g. Centimeter or inches? If not, could this be added?

**Comment by ppete2** [comment]
I don't think I'll add this. What maps and what use case are you talking about where it's important to have finer resolution than 1 m ?

**Comment by Mudo121Bbc** [comment]
Thanks for the fast reply. I use Leaflet for technical drawings and then the maps is not that big, with sometimes just a few meters or less. That's why measuring in centimeters would be really helpful. To measure only in centimeter would be already really nice, inches is currently not important.

Or is there somehow an option, where I can define my own unit?

**Comment by ppete2** [comment]
Do you have some exmples to demonstrate? For all maps I know even in their highest zoom a resolution of 1 m is just a few millimeters on the screen. And usally for most use cases it's enough to know if the width of a house is 10m or 11m. I'm not sure if Leaflet and this pulgin is the correct tool for technical / GIS, high-prescision drawings.

**Comment by Mudo121Bbc** [comment]
I think you are right. I also struggle a bit getting the Plugin to work, but I work with Angular. Maybe I try some other plugins. Thanks for the Help though!
