### ISSUE TITLE
Any way to use custom control to programmatically enable/disable measuring functionality?

### ISSUE THREAD

**Issue by smellyshovel** [ppete2/Leaflet.PolylineMeasure#85]
Hi. Thanks for the awesome tool.

I'm just wondering whether it's possible to programmatically enable/disable the measuring fuctionality.

```
L.control
        .polylineMeasure({
          position: "bottomright",
          unit: "meters",
        })
        .addTo(this.map);
```

This is what I'm using now and I want to be able to do something like this:

```
L.PolylineMeasure.enable(); // or .disable()
```

Is it possible to achieve that?

**Comment by ppete2** [comment]
Hi,

well I think it's possible to simulate pressing the control button by calling the method
`this._toggleMeasure();`
or maybe also working
`L.control.polylineMeasure._toggleMeasure();`

So you have to do a little bit of fiddling to make this work

**Comment by smellyshovel** [comment]
@ppete2 Thanks for the tip (and quick response) :+1: . I'll try and will let you know whether it worked.

**Comment by smellyshovel** [comment]
@ppete2 

So the following code works.

```
this.measureTool = L.control
        .polylineMeasure({
          position: "bottomright",
          unit: "meters",
        })
        .addTo(this.map);

// <...>

// calling this one when needed
toggleMeasurement() {
  this.measureTool._toggleMeasure();
}
```

But I think I found a bug. Even if I'm using the standard control, look what happens when instead of finishing the path and then clicking the button to disable measurement, I click the button *while* still building the path:

![measure-bug](https://user-images.githubusercontent.com/9782236/140302102-9e34de21-58a1-4263-808e-48a50d4b19bb.gif)

The same thing happens for the custom control as well.

I can attach the full error log if you need it (though that is not the gratest option since it might accidentally disclose some NDA-related data).

Here's the error instead:

![Uploading Screenshot_20211104_135824.png…]()

Please, tell me if you need any additional information. Would be happy to help.

And yes, thank you for your help of couse!

**Comment by ppete2** [comment]
Hi, is this just occuring with your own code? Ot in other words: Is this also happening if you use Demo 2 or Demo 3 for example?
(I used Demo 2 and cannot reproduce the bug)

**Comment by smellyshovel** [comment]
@ppete2 no, it happens with neither of them. For some reason it's only my code.

It's not crucial, everything seems to work just fine (even with the error thrown), but would still be nice to get rid of the error. Any ideas over why can that happen and how to solve the issue?

Once again, huge thanks for your participation!

**Comment by ppete2** [comment]
Sorry, I'm not able to analyze what's causing the error messages. You've to contact a JS-expert for example in a JS forum to help you with this error messages in combination with your script (init-map.common.js)

**Comment by smellyshovel** [comment]
@ppete2 Yeah, OK. Anyway, thanks for you help :+1:
