### ISSUE TITLE
How to integrate this plugin with Angular?

### ISSUE THREAD

**Issue by ferily7** [ppete2/Leaflet.PolylineMeasure#86]
I'm using Angular for my project and using ngx-leaflet. I want to use this plugin for my project as well but see that it's in JavaScript.. Is there any way to integrate this library with angular? Or is there somewhere I can go to get some help with this?

**Comment by ppete2** [comment]
Sorry, I'cant help you with your question. You've to ask in a Angular- or in a Leaflet forum for help.
