### ISSUE TITLE
seed() is not a function

### ISSUE THREAD

**Issue by cybergears** [ppete2/Leaflet.PolylineMeasure#87]
I am implementing this plugin in vue js 
The plugin works fine but when i try to seed the data  it throws the error. 
i have installed this plugin using npm from this url https://www.npmjs.com/package/leaflet.polylinemeasure?activeTab=readme

kindly help

**Comment by ppete2** [comment]
I'm not sure if this is the latest version of the plugin, so for testing: could you try to use the latest version from the original site: https://github.com/ppete2/Leaflet.PolylineMeasure

Please also provide your code which you used to seed data.

**Comment by cybergears** [comment]
Thankyou for the response. I just found that the version i am using  is old . I will update to the latest version !
