### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by deeg** [ppete2/Leaflet.PolylineMeasure#9]
Is there any chance you could publish this on npm? It seems like you have a package.json file but I get a 404 when trying to install  `leaflet.polylinemeasure`.

**Comment by ppete2** [comment]
To be honest, I haven't ever worked with "npm-stuff". If somebody is interested in making my plugin being "published on npm", you are welcome. But you have do create the needed files yourself, offer them via Pull request and I'll finally merge them with the Repo.
