### ISSUE TITLE
Change the units to residential land measurement unit

### ISSUE THREAD

**Issue by nanakomeah** [ppete2/Leaflet.PolylineMeasure#90]
Is it possible to get or change the unit to these format: 

- meter square (m²)
- acres
- square feet (feet²) 
- and hectares 

instead of the kilometer, Below is a link of a site that uses the exact units, Would be much grateful if you help me achieve this, Thanks 

https://www.daftlogic.com/projects-google-maps-area-calculator-tool.htm

**Comment by ppete2** [comment]
Sorry, the purpose of this plugin is just to measure distances - no areas.
