### ISSUE TITLE
Disable adding new points after you finish drawing 

### ISSUE THREAD

**Issue by kambanwait** [ppete2/Leaflet.PolylineMeasure#91]
Is it possible to stop the user from adding a new point to their drawn polylines? I see that demo 5 doesn't allow them to move the poly lines drawn on the map but I can't see a method or option for me to disable that particular feature without editing the source code (which I don't want to do)

**Comment by ppete2** [comment]
Could you please explain more in detail what isn't working as intended in Demo 5. And is this also a problem for example in Demo 1 or just in Demo 5 ?
If you want to move drawn points in Demo 5 you first have to turn on PolylineMeasure on the control in the upper left
