### ISSUE TITLE
Get segment distance, headings and total distance

### ISSUE THREAD

**Issue by vitoto9010** [ppete2/Leaflet.PolylineMeasure#93]
Hello, im sorry if this already asked but, is there anyway to get a segment data?

![image](https://user-images.githubusercontent.com/17419789/190963749-41ec4bdf-1cec-4c6f-8f93-7034d24065a2.png)

example of this is i want to get the headings (105 and 194), segment distance (+264 nm or 264 or raw distance that i can convert to nautical miles) and also total distance.

Thank You.

**Comment by ppete2** [comment]
No, there's no data export. It's a view-only addon.

**Comment by vitoto9010** [comment]
alright then, thank you very much for your time!
