### ISSUE TITLE
Add arrow colour option

### ISSUE THREAD

**Issue by luojinzhang** [ppete2/Leaflet.PolylineMeasure#94]
Hi,
This is a very nice project. Just a suggestion, you can add a colour option:
```html: `<div style = 'color: ${this.options.arrowColor}; font-size: 16px; line-height: 16px; vertical-align:top; transform: rotate(${cssAngle}deg)'>&#x27a4;</div>```

**Comment by ppete2** [comment]
I added this option, please have a look at the new version
